Blue-Jay: TimeBasedRecommendor/TimeBasedRecommendor/DateTime.cpp File Reference
TimeBasedRecommendor/TimeBasedRecommendor/DateTime.cpp File Reference
#include "stdafx.h"
#include "DateTime.h"
#include <time.h>
#include <string>
#include <iostream>
#include <sstream>
Functions
bool strictlyChronologicallyOrdered (const DateTime &t1, const DateTime &t2)
Function Documentation
bool strictlyChronologicallyOrdered (const DateTime & t1, const DateTime & t2)
References DateTime::timeUntil().
Referenced by MovingAverage::getCorrelationsFor(), ParticipationMovingAverage::getCurrentValue(), RatingMovingAverage::getValueAt(), ParticipationMovingAverage::getValueAt(), RatingPrecedes::operator()(), ParticipationPrecedes::operator()(), and TimeBasedRecommendor::readFile().