Blue-Jay: MovingAverage Class Reference
MovingAverage Class Reference
#include <MovingAverage.h>
Public Member Functions
MovingAverage (void)
virtual std::pair
< Distribution, int > getValueAt (DateTime when, bool strictlyEarlier)
virtual Distribution getCurrentValue (DateTime when, bool strictlyEarlier)
std::pair< std::vector
< Datapoint >, double > getCorrelationsFor (RatingMovingAverage &other, DateTime startTime)
void setName (Name newName)
Name getName (void)
void setOwnerName (Name newName)
Name getOwnerName (void)
virtual bool isAParticipationMovingAverage (void)
virtual DateTime getLatestDate (void)
Constructor & Destructor Documentation
MovingAverage::MovingAverage (void)
Member Function Documentation
pair< vector< Datapoint >, double > MovingAverage::getCorrelationsFor (RatingMovingAverage & other, DateTime startTime)
References RatingMovingAverage::getRatings(), and strictlyChronologicallyOrdered().
Distribution MovingAverage::getCurrentValue (DateTime when, bool strictlyEarlier) [virtual]
Reimplemented in ParticipationMovingAverage.
DateTime MovingAverage::getLatestDate (void) [virtual]
Reimplemented in ParticipationMovingAverage, and RatingMovingAverage.
Name MovingAverage::getName (void)
Name MovingAverage::getOwnerName (void)
Referenced by PredictionLink::PredictionLink().
pair< Distribution, int > MovingAverage::getValueAt (DateTime when, bool strictlyEarlier) [virtual]
Reimplemented in ParticipationMovingAverage, and RatingMovingAverage.
bool MovingAverage::isAParticipationMovingAverage (void) [virtual]
Reimplemented in ParticipationMovingAverage.
Referenced by PredictionLink::PredictionLink().
void MovingAverage::setName (Name newName)
void MovingAverage::setOwnerName (Name newName)
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/MovingAverage.h
TimeBasedRecommendor/TimeBasedRecommendor/MovingAverage.cpp