Blue-Jay: PredictionLink Class Reference
PredictionLink Class Reference
#include <PredictionLink.h>
Public Member Functions
PredictionLink (void)
PredictionLink (MovingAverage *input, RatingMovingAverage *output)
void initializeDecreasing (void)
void update (void)
Distribution guess (DateTime when)
Constructor & Destructor Documentation
PredictionLink::PredictionLink (void)
PredictionLink::PredictionLink (MovingAverage * input, RatingMovingAverage * output)
References MovingAverage::getOwnerName(), and MovingAverage::isAParticipationMovingAverage().
Member Function Documentation
Distribution PredictionLink::guess (DateTime when)
References Distribution::getMean(), and Distribution::getStdDev().
void PredictionLink::initializeDecreasing (void)
void PredictionLink::update (void)
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/PredictionLink.h
TimeBasedRecommendor/TimeBasedRecommendor/PredictionLink.cpp