Blue-Jay: DateTime Class Reference
DateTime Class Reference
#include <DateTime.h>
Public Member Functions
DateTime (void)
DateTime (std::string yyyymmddhhmmss)
DateTime datePlusDuration (double numSeconds)
void setComponents (std::string yyyymmddhhmmss)
std::string stringVersion (void) const
double timeUntil (const DateTime &other) const
Constructor & Destructor Documentation
DateTime::DateTime (void)
DateTime::DateTime (std::string yyyymmddhhmmss)
Member Function Documentation
DateTime DateTime::datePlusDuration (double numSeconds)
Referenced by ParticipationMovingAverage::getCurrentValue(), and RatingMovingAverage::getValueAt().
void DateTime::setComponents (std::string yyyymmddhhmmss)
string DateTime::stringVersion (void) const
Referenced by ParticipationMovingAverage::getValueAt().
double DateTime::timeUntil (const DateTime & other) const
Referenced by ParticipationMovingAverage::addParticipationInterval(), ParticipationMovingAverage::getCurrentValue(), Candidate::getIdleDuration(), RatingMovingAverage::getValueAt(), ParticipationMovingAverage::getValueAt(), and strictlyChronologicallyOrdered().
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/DateTime.h
TimeBasedRecommendor/TimeBasedRecommendor/DateTime.cpp