Blue-Jay: ParticipationMovingAverage Class Reference
ParticipationMovingAverage Class Reference
#include <ParticipationMovingAverage.h>
Public Member Functions
ParticipationMovingAverage ()
void addParticipationInterval (Participation interval)
std::pair< Distribution, int > getValueAt (DateTime when, bool strictlyEarlier)
Distribution getCurrentValue (DateTime when, bool strictlyEarlier) override
bool isAParticipationMovingAverage (void) override
DateTime getLatestDate (void) override
int getNumParticipations (void)
Constructor & Destructor Documentation
ParticipationMovingAverage::ParticipationMovingAverage ()
Member Function Documentation
void ParticipationMovingAverage::addParticipationInterval (Participation interval)
References Participation::getEndTime(), Participation::getIntensity(), Participation::getStartTime(), Participation::setIntensity(), and DateTime::timeUntil().
Distribution ParticipationMovingAverage::getCurrentValue (DateTime when, bool strictlyEarlier) [override, virtual]
Reimplemented from MovingAverage.
References DateTime::datePlusDuration(), Participation::getEndTime(), Participation::getStartTime(), strictlyChronologicallyOrdered(), and DateTime::timeUntil().
DateTime ParticipationMovingAverage::getLatestDate (void) [override, virtual]
Reimplemented from MovingAverage.
Referenced by Candidate::getIdleDuration().
int ParticipationMovingAverage::getNumParticipations (void)
Referenced by Candidate::getIdleDuration().
pair< Distribution, int > ParticipationMovingAverage::getValueAt (DateTime when, bool strictlyEarlier) [virtual]
Reimplemented from MovingAverage.
References Participation::getEndTime(), Participation::getStartTime(), strictlyChronologicallyOrdered(), DateTime::stringVersion(), and DateTime::timeUntil().
bool ParticipationMovingAverage::isAParticipationMovingAverage (void) [override, virtual]
Reimplemented from MovingAverage.
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/ParticipationMovingAverage.h
TimeBasedRecommendor/TimeBasedRecommendor/ParticipationMovingAverage.cpp