Blue-Jay: Rating Class Reference
Rating Class Reference
#include <Rating.h>
Public Member Functions
Rating (void)
void setActivity (Name name)
Name getActivity (void) const
void setDate (DateTime time)
const DateTime & getDate (void) const
void setScore (double newValue)
double getScore (void)
void setWeight (double newWeight)
double getWeight (void)
Constructor & Destructor Documentation
Rating::Rating (void)
Member Function Documentation
Name Rating::getActivity (void) const
Referenced by RatingPrecedes::operator()().
const DateTime & Rating::getDate (void) const
Referenced by RatingMovingAverage::addRating(), RatingMovingAverage::getValueAt(), and RatingPrecedes::operator()().
double Rating::getScore (void)
Referenced by RatingMovingAverage::addRating(), and RatingMovingAverage::getValueAt().
double Rating::getWeight (void)
Referenced by RatingMovingAverage::addRating(), and RatingMovingAverage::getValueAt().
void Rating::setActivity (Name name)
Referenced by TimeBasedRecommendor::readFile().
void Rating::setDate (DateTime time)
Referenced by RatingMovingAverage::addRating(), and TimeBasedRecommendor::readFile().
void Rating::setScore (double newValue)
Referenced by RatingMovingAverage::addRating(), and TimeBasedRecommendor::readFile().
void Rating::setWeight (double newWeight)
Referenced by RatingMovingAverage::addRating().
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/Rating.h
TimeBasedRecommendor/TimeBasedRecommendor/Rating.cpp