Blue-Jay: Participation Class Reference
Participation Class Reference
#include <Participation.h>
Public Member Functions
Participation ()
void setStartTime (DateTime start)
DateTime getStartTime (void)
void setEndTime (DateTime end)
DateTime getEndTime (void) const
void setActivityName (Name name)
const Name & getActivityName (void)
void setIntensity (double intensity)
double getIntensity (void)
Constructor & Destructor Documentation
Participation::Participation ()
Member Function Documentation
const Name & Participation::getActivityName (void)
DateTime Participation::getEndTime (void) const
Referenced by ParticipationMovingAverage::addParticipationInterval(), ParticipationMovingAverage::getCurrentValue(), ParticipationMovingAverage::getValueAt(), Candidate::giveParticipation(), and ParticipationPrecedes::operator()().
double Participation::getIntensity (void)
Referenced by ParticipationMovingAverage::addParticipationInterval().
DateTime Participation::getStartTime (void)
Referenced by ParticipationMovingAverage::addParticipationInterval(), ParticipationMovingAverage::getCurrentValue(), and ParticipationMovingAverage::getValueAt().
void Participation::setActivityName (Name name)
Referenced by TimeBasedRecommendor::readFile().
void Participation::setEndTime (DateTime end)
Referenced by TimeBasedRecommendor::readFile().
void Participation::setIntensity (double intensity)
Referenced by ParticipationMovingAverage::addParticipationInterval().
void Participation::setStartTime (DateTime start)
Referenced by TimeBasedRecommendor::readFile().
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/Participation.h
TimeBasedRecommendor/TimeBasedRecommendor/Participation.cpp