Blue-Jay: Candidate Class Reference
Candidate Class Reference
#include <Candidate.h>
Public Member Functions
Candidate (Name title)
Candidate (void)
void setName (Name newName)
Name getName (void)
void addParent (Name newName)
void addParent (Candidate *newCandidate)
void addChild (Candidate *newChild)
std::vector< Name > * getParentNames (void)
std::vector< Candidate * > * getParents (void)
std::vector< Candidate * > * getChildren (void)
void giveRating (Rating rating)
void giveParticipation (Participation participation)
int getNumRatingEstimators (void)
MovingAverage * getRatingEstimatorAtIndex (int index)
int getNumFrequencyEstimators (void)
ParticipationMovingAverage * getFrequencyEstimatorAtIndex (int index)
RatingMovingAverage * getActualRatingHistory (void)
Distribution getCurrentRating (void)
void setCurrentRating (Distribution value)
Distribution getCurrentRefinedRating (void)
void setCurrentRefinedRating (Distribution value)
bool needToUpdateParentPointers (void)
void setDiscoveryDate (DateTime when)
double getIdleDuration (DateTime when)
double getAverageRating (void)
Constructor & Destructor Documentation
Candidate::Candidate (Name title)
Candidate::Candidate (void)
Member Function Documentation
void Candidate::addChild (Candidate * newChild)
void Candidate::addParent (Name newName)
Referenced by TimeBasedRecommendor::readFile().
void Candidate::addParent (Candidate * newCandidate)
RatingMovingAverage * Candidate::getActualRatingHistory (void)
double Candidate::getAverageRating (void)
std::vector< Candidate * > * Candidate::getChildren (void)
Distribution Candidate::getCurrentRating (void)
Distribution Candidate::getCurrentRefinedRating (void)
ParticipationMovingAverage * Candidate::getFrequencyEstimatorAtIndex (int index)
double Candidate::getIdleDuration (DateTime when)
References ParticipationMovingAverage::getLatestDate(), ParticipationMovingAverage::getNumParticipations(), and DateTime::timeUntil().
Name Candidate::getName (void)
int Candidate::getNumFrequencyEstimators (void)
int Candidate::getNumRatingEstimators (void)
std::vector< Name > * Candidate::getParentNames (void)
std::vector< Candidate * > * Candidate::getParents (void)
MovingAverage * Candidate::getRatingEstimatorAtIndex (int index)
void Candidate::giveParticipation (Participation participation)
References Participation::getEndTime().
void Candidate::giveRating (Rating rating)
bool Candidate::needToUpdateParentPointers (void)
void Candidate::setCurrentRating (Distribution value)
void Candidate::setCurrentRefinedRating (Distribution value)
void Candidate::setDiscoveryDate (DateTime when)
Referenced by TimeBasedRecommendor::readFile().
void Candidate::setName (Name newName)
Referenced by TimeBasedRecommendor::readFile().
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/Candidate.h
TimeBasedRecommendor/TimeBasedRecommendor/Candidate.cpp