Blue-Jay: TimeBasedRecommendor Class Reference
TimeBasedRecommendor Class Reference
#include <TimeBasedRecommendor.h>
Public Member Functions
TimeBasedRecommendor ()
void parseArguments (ArgumentList *arguments)
void readFile (char *fileName)
Constructor & Destructor Documentation
TimeBasedRecommendor::TimeBasedRecommendor ()
Member Function Documentation
void TimeBasedRecommendor::parseArguments (ArgumentList * arguments)
References ArgumentList::getArgument(), and ArgumentList::getNumArguments().
Referenced by main().
void TimeBasedRecommendor::readFile (char * fileName)
References Candidate::addParent(), Name::appendChar(), Name::clear(), Name::getName(), Rating::setActivity(), Participation::setActivityName(), Rating::setDate(), Candidate::setDiscoveryDate(), Participation::setEndTime(), Candidate::setName(), Rating::setScore(), Participation::setStartTime(), and strictlyChronologicallyOrdered().
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/TimeBasedRecommendor.h
TimeBasedRecommendor/TimeBasedRecommendor/TimeBasedRecommendor.cpp