Blue-Jay: RatingMovingAverage Class Reference
RatingMovingAverage Class Reference
#include <RatingMovingAverage.h>
Public Member Functions
RatingMovingAverage ()
void addRating (Rating rating)
std::pair< Distribution, int > getValueAt (DateTime when, bool strictlyEarlier)
const std::vector< Rating > & getRatings (void)
int getNumRatings (void)
double getAverageValue (void)
DateTime getLatestDate (void) override
Constructor & Destructor Documentation
RatingMovingAverage::RatingMovingAverage ()
Member Function Documentation
void RatingMovingAverage::addRating (Rating rating)
References Rating::getDate(), Rating::getScore(), Rating::getWeight(), Rating::setDate(), Rating::setScore(), and Rating::setWeight().
double RatingMovingAverage::getAverageValue (void)
DateTime RatingMovingAverage::getLatestDate (void) [override, virtual]
Reimplemented from MovingAverage.
int RatingMovingAverage::getNumRatings (void)
const std::vector< Rating > & RatingMovingAverage::getRatings (void)
Referenced by MovingAverage::getCorrelationsFor().
pair< Distribution, int > RatingMovingAverage::getValueAt (DateTime when, bool strictlyEarlier) [virtual]
Reimplemented from MovingAverage.
References DateTime::datePlusDuration(), Rating::getDate(), Rating::getScore(), Rating::getWeight(), strictlyChronologicallyOrdered(), and DateTime::timeUntil().
The documentation for this class was generated from the following files:
TimeBasedRecommendor/TimeBasedRecommendor/RatingMovingAverage.h
TimeBasedRecommendor/TimeBasedRecommendor/RatingMovingAverage.cpp